apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitops-lab
  namespace: gitops-lab
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  interval: 5m
  releaseName: gitops-lab
  chart:
    spec:
      chart: ./artifacts/gitops-lab/charts/gitops-lab
